FROM minio/minio:RELEASE.2020-10-03T02-19-42Z

USER root
#COPY ./Storage/minio/storage /minio-image/storage

#RUN wget https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x mc

#RUN curl --silent -O https://dl.min.io/client/mc/release/linux-amd64/mc && \
#    chmod +x mc  \
#    && mv mc /usr/local/bin